### ISSUE TITLE
Breaking changes since 1.5.1

### ISSUE THREAD

**Issue by radiantone** [nathancahill/split#168] opened 2018-11-05 20:10 UTC
Hi,
   This is just a heads up that we had to revert to version 1.5.1 as recent changes have caused some layout and rendering issues in our tool. We have a boostrap/css app with tabs and multiple splits (e.g. a vertical split, then the top region has a horizontal split). With the latest release (and maybe a couple behind that) the split bar inside the second tab (not shown initially) did not render (no grab bar). In another tool, the component inside a split div did not consume all the space as it did before.

Sorry I do not have specifics yet, but will dig deeper and post them here. Thanks for an awesome library!

**Comment by nathancahill** [comment] 2018-11-05 20:32
To clarify, it's working in 1.5.1?

**Comment by radiantone** [comment] 2018-11-05 20:33
Yes

**Comment by nathancahill** [comment] 2018-11-05 20:34
Were you able to try with any other versions, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7 to try to pinpoint the breaking change?

**Comment by nathancahill** [comment] 2018-11-05 20:35
ie.. if 1.5.2 breaks, that narrows down the issue.

**Comment by radiantone** [comment] 2018-11-05 20:36
I tried a couple others but let me try 1.5.2

**Comment by radiantone** [comment] 2018-11-05 20:44
Actually, after some more study, it looks like only 1.5.7 breaks our app.

**Comment by nathancahill** [comment] 2018-11-05 20:47
Great, thanks for taking the time to test that. It's very helpful. I believe I know what the issue is. Does this only happen in the tab that isn't initially shown?

**Comment by radiantone** [comment] 2018-11-05 21:29
It seems so. Yes.

**Comment by nathancahill** [comment] 2018-11-05 21:45
Thanks. It looks like I caused a conflict with Bootstrap tabs. Before you change to that tab, can type in the browser console:

```
document.querySelector('#view-1').parentElement.clientWidth
```

Where `#view-1` is one of the elements in the split in the tab?

**Comment by radiantone** [comment] 2018-11-05 21:54
> document.querySelector('#aipane2').parentElement.clientWidth
0

**Comment by nathancahill** [comment] 2018-11-05 21:56
Perfect, that's what I was expecting. Fix coming soon!

**Comment by nathancahill** [comment] 2018-11-05 22:06
Please try the latest release, 1.5.9. This should fix the issue.

**Comment by UmangThapliyal** [comment] 2018-11-06 07:08
Hello, i am facing the same issue, I have tried 1.5.9 also

**Comment by radiantone** [comment] 2018-11-06 11:48
That botched the visible tab now.
![splitjs-1](https://user-images.githubusercontent.com/25509097/48062414-f4e4ac00-e18f-11e8-8031-c836d4e41fb4.png)

**Comment by UmangThapliyal** [comment] 2018-11-06 12:09
I faced the same issue and when i moved back to previous version it gets fixed

**Comment by nathancahill** [comment] 2018-11-06 14:52
@radiantone is there a chance you could share the code that shows this issue? Or @UmangThapliyal?

**Comment by radiantone** [comment] 2018-11-06 15:10
It's just normal split calls, but the divs live inside bootstrap layouts

` var sidebar = Split(['#sidebar', '#workspace'], {
            sizes: [30, 70],
            direction: 'horizontal'
        });
        var codebars = Split(['#jscode', '#htmlcode'], {
            sizes: [50, 50],
            direction: 'horizontal'
        });
        Split(['#aipane1', '#aipane2'], {
            sizes: [50, 50],
            direction: 'horizontal'
        });
        Split(['#aipanetop', '#aipanebottom'], {
            sizes: [65, 35],
            direction: 'vertical'
        });
        Split(['#lingpanetop', '#lingpanebottom'], {
            sizes: [65, 35],
            direction: 'vertical'
        });
        Split(['#coderegion', '#previewregion'], {
            sizes: [55, 45],
            direction: 'vertical'
        });
        Split(['#pagecoderegion', '#pageframe'], {
            sizes: [50, 50],
            direction: 'vertical'
        });`

**Comment by nathancahill** [comment] 2018-11-06 15:22
Right, can you share the relevant Bootstrap layout? That's the part that seems to be conflicting.

**Comment by nathancahill** [comment] 2018-11-06 15:47
Ok, a better way might be to take a screenshot of the Styles inspector in the debugger. Both of the parent element and one of the split elements. Thanks!

**Comment by radiantone** [comment] 2018-11-06 16:04
Here is one shot of working 1.5.6 and one of 1.5.9 (which has no gutters even).
![splitjs-good](https://user-images.githubusercontent.com/25509097/48076703-c4af0480-e1b3-11e8-8903-ad8eba0349b3.png)
![splitjs-bad](https://user-images.githubusercontent.com/25509097/48076705-c7115e80-e1b3-11e8-9f15-f0006f7e88e2.png)

**Comment by nathancahill** [comment] 2018-11-06 16:07
Very helpful. Are there any errors in the console?

**Comment by radiantone** [comment] 2018-11-06 16:11
Refused to execute script from 'https://unpkg.com/split.js@1.5.9/split.min.js' because its MIME type ('text/plain')

**Comment by radiantone** [comment] 2018-11-06 16:14
Ok, things are working now in 1.5.9. Thank you

**Comment by nathancahill** [comment] 2018-11-06 16:50
Great. Updated the URL in the readme too. @UmangThapliyal does that solve your problem too?

```
https://unpkg.com/split.js/dist/split.min.js
```

**Comment by nathancahill** [comment] 2018-11-06 19:18
Closing this for now. @UmangThapliyal if you have another issue please open another issue.

**Closed by nathancahill** 2018-11-06 19:18 UTC
Labels: split.js
