### ISSUE TITLE
QUESTION: Hoe to set minimum and maximum width to individual divs in react-split-grid

### ISSUE THREAD

**Issue by kayesn786** [nathancahill/split#389] opened 2020-10-12 08:45 UTC
Hi,
I went through the props, i could find columnMinSizes for setting minim width to individual divs. But couldnt do so.
Someone can help me how to use it.

Thanks

**Comment by nathancahill** [comment] 2021-03-28 17:36
At this moment there is no support for max-width, duplicate of #66

**Closed by nathancahill** 2021-03-28 17:36 UTC
Labels: duplicate
